export type BadgeRarity = 'Common' | 'Rare' | 'Epic' | 'Legendary' | 'Developer';

export interface BadgeConfig {
  id: string;
  name: string;
  defaultName: string;
  rarity: BadgeRarity;
  price: number;
  icon: string;
  bgGradient: string;
  borderClass: string;
  textColorClass: string;
  glowColor: string;
  shadowClass: string;
  rarityBadgeClass: string;
  description: string;
  hasShine?: boolean;
  hasRainbowPulse?: boolean;
}

export const ALL_BADGES: BadgeConfig[] = [
  // --- COMMON (2,000 Coins) - Polos tanpa efek ---
  {
    id: 'common_red',
    name: 'Common Merah',
    defaultName: 'Common Merah',
    rarity: 'Common',
    price: 2000,
    icon: '🔴',
    bgGradient: 'bg-red-700',
    borderClass: 'border-red-500',
    textColorClass: 'text-white',
    glowColor: 'rgba(239, 68, 68, 0.3)',
    shadowClass: 'shadow-sm shadow-red-900/30',
    rarityBadgeClass: 'text-red-300 border-red-500/30 bg-red-950/40',
    description: 'Badge Common warna Merah polos tanpa efek.',
  },
  {
    id: 'common_blue',
    name: 'Common Biru',
    defaultName: 'Common Biru',
    rarity: 'Common',
    price: 2000,
    icon: '🔵',
    bgGradient: 'bg-blue-700',
    borderClass: 'border-blue-500',
    textColorClass: 'text-white',
    glowColor: 'rgba(59, 130, 246, 0.3)',
    shadowClass: 'shadow-sm shadow-blue-900/30',
    rarityBadgeClass: 'text-blue-300 border-blue-500/30 bg-blue-950/40',
    description: 'Badge Common warna Biru polos tanpa efek.',
  },
  {
    id: 'common_green',
    name: 'Common Hijau',
    defaultName: 'Common Hijau',
    rarity: 'Common',
    price: 2000,
    icon: '🟢',
    bgGradient: 'bg-emerald-700',
    borderClass: 'border-emerald-500',
    textColorClass: 'text-white',
    glowColor: 'rgba(16, 185, 129, 0.3)',
    shadowClass: 'shadow-sm shadow-emerald-900/30',
    rarityBadgeClass: 'text-emerald-300 border-emerald-500/30 bg-emerald-950/40',
    description: 'Badge Common warna Hijau polos tanpa efek.',
  },
  {
    id: 'common_yellow',
    name: 'Common Kuning',
    defaultName: 'Common Kuning',
    rarity: 'Common',
    price: 2000,
    icon: '🟡',
    bgGradient: 'bg-amber-600',
    borderClass: 'border-amber-400',
    textColorClass: 'text-slate-950 font-bold',
    glowColor: 'rgba(245, 158, 11, 0.3)',
    shadowClass: 'shadow-sm shadow-amber-900/30',
    rarityBadgeClass: 'text-amber-300 border-amber-500/30 bg-amber-950/40',
    description: 'Badge Common warna Kuning polos tanpa efek.',
  },

  // --- RARE (5,000 Coins) - Minimal 5 Kombinasi Warna Elegan ---
  {
    id: 'rare_red_blue',
    name: 'Rare Merah + Biru',
    defaultName: 'Rare Merah + Biru',
    rarity: 'Rare',
    price: 5000,
    icon: '🔮',
    bgGradient: 'bg-gradient-to-r from-red-600 via-purple-600 to-blue-600',
    borderClass: 'border-purple-400/80',
    textColorClass: 'text-white',
    glowColor: 'rgba(168, 85, 247, 0.5)',
    shadowClass: 'shadow-md shadow-purple-600/30',
    rarityBadgeClass: 'text-purple-300 border-purple-500/40 bg-purple-950/50',
    description: 'Kombinasi elegan gradasi Merah dan Biru.',
  },
  {
    id: 'rare_yellow_green',
    name: 'Rare Kuning + Hijau',
    defaultName: 'Rare Kuning + Hijau',
    rarity: 'Rare',
    price: 5000,
    icon: '🍃',
    bgGradient: 'bg-gradient-to-r from-amber-500 via-lime-500 to-emerald-600',
    borderClass: 'border-lime-300/80',
    textColorClass: 'text-slate-950 font-bold',
    glowColor: 'rgba(132, 204, 22, 0.5)',
    shadowClass: 'shadow-md shadow-lime-600/30',
    rarityBadgeClass: 'text-lime-300 border-lime-500/40 bg-lime-950/50',
    description: 'Kombinasi segar gradasi Kuning dan Hijau.',
  },
  {
    id: 'rare_purple_blue',
    name: 'Rare Ungu + Biru',
    defaultName: 'Rare Ungu + Biru',
    rarity: 'Rare',
    price: 5000,
    icon: '🌌',
    bgGradient: 'bg-gradient-to-r from-purple-700 via-indigo-600 to-sky-600',
    borderClass: 'border-indigo-300/80',
    textColorClass: 'text-white',
    glowColor: 'rgba(99, 102, 241, 0.5)',
    shadowClass: 'shadow-md shadow-indigo-600/30',
    rarityBadgeClass: 'text-indigo-300 border-indigo-500/40 bg-indigo-950/50',
    description: 'Kombinasi cosmos gradasi Ungu dan Biru.',
  },
  {
    id: 'rare_red_purple',
    name: 'Rare Merah + Ungu',
    defaultName: 'Rare Merah + Ungu',
    rarity: 'Rare',
    price: 5000,
    icon: '🍷',
    bgGradient: 'bg-gradient-to-r from-rose-700 via-pink-600 to-purple-800',
    borderClass: 'border-pink-400/80',
    textColorClass: 'text-white',
    glowColor: 'rgba(236, 72, 153, 0.5)',
    shadowClass: 'shadow-md shadow-pink-600/30',
    rarityBadgeClass: 'text-pink-300 border-pink-500/40 bg-pink-950/50',
    description: 'Kombinasi mewah gradasi Merah dan Ungu.',
  },
  {
    id: 'rare_cyan_blue',
    name: 'Rare Cyan + Biru',
    defaultName: 'Rare Cyan + Biru',
    rarity: 'Rare',
    price: 5000,
    icon: '💎',
    bgGradient: 'bg-gradient-to-r from-cyan-500 via-sky-500 to-blue-700',
    borderClass: 'border-cyan-300/80',
    textColorClass: 'text-slate-950 font-bold',
    glowColor: 'rgba(6, 182, 212, 0.5)',
    shadowClass: 'shadow-md shadow-cyan-600/30',
    rarityBadgeClass: 'text-cyan-300 border-cyan-500/40 bg-cyan-950/50',
    description: 'Kombinasi kristal gradasi Cyan dan Biru.',
  },

  // --- EPIC (20,000 Coins) - Kilatan Elegan Setiap ±2 Detik ---
  {
    id: 'epic_red',
    name: 'Epic Merah',
    defaultName: 'Epic Merah',
    rarity: 'Epic',
    price: 20000,
    icon: '🔥',
    bgGradient: 'bg-gradient-to-r from-red-600 via-rose-500 to-red-700',
    borderClass: 'border-rose-300/90',
    textColorClass: 'text-white font-extrabold',
    glowColor: 'rgba(244, 63, 94, 0.7)',
    shadowClass: 'shadow-lg shadow-rose-600/40',
    rarityBadgeClass: 'text-rose-300 border-rose-500/40 bg-rose-950/60',
    description: 'Merah Epic berapi-api dengan efek kilatan berkala.',
    hasShine: true,
  },
  {
    id: 'epic_blue',
    name: 'Epic Biru',
    defaultName: 'Epic Biru',
    rarity: 'Epic',
    price: 20000,
    icon: '⚡',
    bgGradient: 'bg-gradient-to-r from-blue-600 via-sky-500 to-indigo-700',
    borderClass: 'border-sky-300/90',
    textColorClass: 'text-white font-extrabold',
    glowColor: 'rgba(14, 165, 233, 0.7)',
    shadowClass: 'shadow-lg shadow-sky-600/40',
    rarityBadgeClass: 'text-sky-300 border-sky-500/40 bg-sky-950/60',
    description: 'Biru Epic kilat petir dengan efek kilatan berkala.',
    hasShine: true,
  },
  {
    id: 'epic_green',
    name: 'Epic Hijau',
    defaultName: 'Epic Hijau',
    rarity: 'Epic',
    price: 20000,
    icon: '🌿',
    bgGradient: 'bg-gradient-to-r from-emerald-600 via-teal-500 to-green-700',
    borderClass: 'border-emerald-300/90',
    textColorClass: 'text-white font-extrabold',
    glowColor: 'rgba(16, 185, 129, 0.7)',
    shadowClass: 'shadow-lg shadow-emerald-600/40',
    rarityBadgeClass: 'text-emerald-300 border-emerald-500/40 bg-emerald-950/60',
    description: 'Hijau Zamrud Epic dengan efek kilatan berkala.',
    hasShine: true,
  },
  {
    id: 'epic_yellow',
    name: 'Epic Kuning',
    defaultName: 'Epic Kuning',
    rarity: 'Epic',
    price: 20000,
    icon: '👑',
    bgGradient: 'bg-gradient-to-r from-amber-500 via-yellow-400 to-amber-600',
    borderClass: 'border-yellow-200',
    textColorClass: 'text-slate-950 font-black',
    glowColor: 'rgba(245, 158, 11, 0.75)',
    shadowClass: 'shadow-lg shadow-amber-500/50',
    rarityBadgeClass: 'text-amber-300 border-amber-500/40 bg-amber-950/60',
    description: 'Emas Kerajaan Epic dengan kilatan koin berdenyut.',
    hasShine: true,
  },
  {
    id: 'epic_purple',
    name: 'Epic Ungu',
    defaultName: 'Epic Ungu',
    rarity: 'Epic',
    price: 20000,
    icon: '🔮',
    bgGradient: 'bg-gradient-to-r from-purple-600 via-fuchsia-500 to-indigo-700',
    borderClass: 'border-fuchsia-300/90',
    textColorClass: 'text-white font-extrabold',
    glowColor: 'rgba(217, 70, 239, 0.7)',
    shadowClass: 'shadow-lg shadow-fuchsia-600/40',
    rarityBadgeClass: 'text-fuchsia-300 border-fuchsia-500/40 bg-fuchsia-950/60',
    description: 'Ungu Epic Mistik dengan kilatan cahaya berkala.',
    hasShine: true,
  },

  // --- LEGENDARY (45,000 Coins) - Rainbow Pulse 5 Warna Menyebar ---
  {
    id: 'legend_rainbow_pulse',
    name: 'Rainbow Pulse',
    defaultName: 'Rainbow Pulse',
    rarity: 'Legendary',
    price: 45000,
    icon: '🌈',
    bgGradient: 'bg-gradient-to-r from-red-500 via-yellow-500 via-emerald-500 via-blue-500 to-purple-600',
    borderClass: 'border-amber-300 animate-pulse',
    textColorClass: 'text-white font-black drop-shadow-md',
    glowColor: 'rgba(236, 72, 153, 0.85)',
    shadowClass: 'shadow-xl shadow-pink-500/50',
    rarityBadgeClass: 'text-amber-200 border-amber-400/60 bg-slate-950/80 font-black uppercase tracking-wider',
    description: '5 Warna: Merah, Kuning, Hijau, Ungu, Biru. Transisi halus, infinity loop menyebar dari tengah.',
    hasShine: true,
    hasRainbowPulse: true,
  },

  // --- DEVELOPER SPECIAL BADGES ---
  {
    id: 'ruby',
    name: 'Ruby Developer',
    defaultName: 'Ruby Developer',
    rarity: 'Developer',
    price: 0,
    icon: '👑',
    bgGradient: 'bg-gradient-to-r from-red-600 via-rose-600 to-purple-700',
    borderClass: 'border-rose-300',
    textColorClass: 'text-white font-black',
    glowColor: 'rgba(225, 29, 72, 0.8)',
    shadowClass: 'shadow-xl shadow-rose-600/50',
    rarityBadgeClass: 'text-rose-300 border-rose-500/50 bg-rose-950/80 font-black',
    description: 'Badge Eksklusif Developer Utama.',
    hasShine: true,
  },
];

export const BADGE_MAP: Record<string, BadgeConfig> = ALL_BADGES.reduce((acc, badge) => {
  acc[badge.id] = badge;
  return acc;
}, {} as Record<string, BadgeConfig>);

export type BadgeThemeId = string;
export const BADGE_THEMES = BADGE_MAP;
